### ISSUE TITLE
How do you run the project in windows?

### ISSUE THREAD

**Issue by rebase-master** [equip/project#11]
Hi,

The command bin/serve is supposed to start the server at the specified port. How does this work on windows command line?

**Comment by bvisness** [comment]
If you have PHP on your `PATH` (as described [here](http://stackoverflow.com/questions/7307548/how-to-access-php-with-the-command-line-on-windows)), then you should be able to run the following in your command prompt:

```
php -S localhost:8000 -t public/ public/index.php
```

You can replace `8000` with a different port if you want.

Or, since Windows 10 [now supports bash](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide), you could try running `bin/serve` from there.
